In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
tomtom = pd.read_csv("./tomtom_conv1_cisbp_t1_allr/tomtom.tsv", sep='\t', header=0, index_col=0, skipfooter=3, engine='python')
tomtom = tomtom[tomtom["q-value"]<0.1][["Target_ID", "q-value"]]
tomtom["Query_ID"] = tomtom.index
tomtom

             Target_ID   q-value   Query_ID
Query_ID
Motif_0    M01680_2.00  0.000302    Motif_0
Motif_0    M08325_2.00  0.002583    Motif_0
Motif_0    M08306_2.00  0.019303    Motif_0
Motif_0    M07646_2.00  0.031692    Motif_0
Motif_0    M08090_2.00  0.056819    Motif_0
...                ...       ...        ...
Motif_127  M09437_2.00  0.093212  Motif_127
Motif_127  M03576_2.00  0.093212  Motif_127
Motif_127  M03996_2.00  0.093212  Motif_127
Motif_127  M09434_2.00  0.093212  Motif_127
Motif_127  M09438_2.00  0.093212  Motif_127

[801 rows x 3 columns]

In [3]:
tomtom.Query_ID.unique().shape

(26,)

In [4]:
anno = pd.read_csv("/media/ggj/Files/mount/NvWA_Final/0_TFBS/CisBP/Homo_sapiens_2019_01/TF_Information.txt", 
                  sep='\t', header=0, index_col=0)

anno = anno[["Motif_ID", "TF_Name", "Family_Name"]]
anno

                 Motif_ID TF_Name Family_Name
TF_ID
T010820_2.00  M02753_2.00  TFAP2B        AP-2
T010820_2.00  M02754_2.00  TFAP2B        AP-2
T010820_2.00  M02755_2.00  TFAP2B        AP-2
T010820_2.00  M04046_2.00  TFAP2B        AP-2
T010820_2.00  M04047_2.00  TFAP2B        AP-2
...                   ...     ...         ...
T350311_2.00  M11439_2.00    NFE4     Unknown
T350312_2.00  M07782_2.00  ZNF487     Unknown
T350313_2.00            .    NME2     Unknown
T350314_2.00            .   DACH1     Unknown
T350315_2.00            .   PCGF2     Unknown

[5861 rows x 3 columns]

In [5]:
tomtom_anno = tomtom.merge(anno, how='inner', left_on="Target_ID", right_on="Motif_ID")
tomtom_anno

,Target_ID,q-value,Query_ID,Motif_ID,TF_Name,Family_Name
0,M08325_2.00,0.002583,Motif_0,M08325_2.00,ZNF22,C2H2 ZF
1,M08325_2.00,0.003428,Motif_8,M08325_2.00,ZNF22,C2H2 ZF
2,M08325_2.00,0.000010,Motif_10,M08325_2.00,ZNF22,C2H2 ZF
3,M08325_2.00,0.000007,Motif_34,M08325_2.00,ZNF22,C2H2 ZF
4,M08325_2.00,0.000065,Motif_35,M08325_2.00,ZNF22,C2H2 ZF
...,...,...,...,...,...,...
609,M04570_2.00,0.078929,Motif_124,M04570_2.00,ZBTB33,C2H2 ZF
610,M00336_2.00,0.022394,Motif_125,M00336_2.00,PAX6,"Homeodomain,Paired box"
611,M08175_2.00,0.007281,Motif_127,M08175_2.00,TEAD2,TEA
612,M03576_2.00,0.093212,Motif_127,M03576_2.00,TEAD3,TEA
613,M09434_2.00,0.093212,Motif_127,M09434_2.00,TEAD1,TEA

In [6]:
tomtom_anno.columns = ["Target_ID", "q-value", "Query_ID", "Motif_ID", "gene_name", "Family_Name"]

In [7]:
tomtom_anno.to_csv("./tomtom_conv1_cisbp_t1_allr/filter_anno_family.csv")